### ISSUE TITLE
Create a cookiecutter to easily bootstrap new distributions

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/retrolab#133]
Since this repo serves as an example to show how to build a custom JupyterLab distribution, there could also be a cookiecutter that would make it handy to create a new project from scratch using a similar structure.

**Comment by molinsp** [comment]
Thanks for creating the issue @jtpio! Even before the cookie-cutter, could you share some guidance on how to get started to create a new JLab distribution from this repo? I'm looking around the files and would benefit from a high-level understanding of how this repo has been set up.

**Comment by jtpio** [comment]
Thanks for the interest!

This is actually one of the main motivations for having this repo in the first place: have a real-world and concrete example of an alternative JupyterLab distribution, that can also be packaged and shipped to end users.

Maybe this could be a good opportunity to bootstrap some documentation for this repo (https://github.com/jupyterlab/retrolab/issues/97), and put the overview there. Folks could then refer to the docs when they want to build a new custom distribution until there is a proper cookiecutter.

A first step would indeed be to have an overview / tour of the repo structure. The main parts for now are:

- the [packages](https://github.com/jupyterlab/retrolab/tree/main/packages) folder: contains the list of extensions (each extension has one or many plugins) that are specific to RetroLab
- the [app](https://github.com/jupyterlab/retrolab/tree/main/app) folder: to build the application package with the static assets (html + js)
  - [index.js](https://github.com/jupyterlab/retrolab/blob/988db2b2f9513a5144e9722951213e3b900bfadf/app/index.js#L69-L183) lists the plugins available on each of the pages (tree, notebooks, edit and terminals). Many of the plugins are actually reused as is from JupyterLab
  - `package.json` and `webpack.config.js` to list dependencies and build the app
- the top-level `package.json` to list scripts and make it easier to develop with `lerna`

**Comment by molinsp** [comment]
Thanks for the answer, very helpful!. I will play around in the coming weeks and if I'm successful will report back and contribute to the docs

**Comment by bollwyvl** [comment]
I've mentioned this in a few places: I :heart: some cookiecutter, for sure (pitch: like cookiecutters, too? try [jupyter_starters](https://github.com/deathbeds/jupyterlab-starters)!) but I think this points at a deeper concern. 

Basically, the description of a lab application e.g. `@mylab/application-top`, consists of a static realization in a `index.js` webpack entrypoint of the eventual dependency injection graph, which then gets realized and extended at runtime by federated extensions. 

While webpack isn't going anywhere for now for generating robustly reusable components of a lab-derived application, I feel like confecting a new custom app eventually shouldn't require a webpack engineering degree.  I would love to see something that moved the set of underlying components even further into a data (and therefore user/administrator, rather than webpack engineer) task.

The runtime interactions between these things are handled, roughly in order of describe-ability:
- lumino tokens (hard singletons)
- lumino commands (an `<id, args>` pair)
- lumino signals (an `<interface, args>` pair)
- lumino messages (don't worry too much about these)
- bespoke extension APIs provided by the extension

The challenge would become formalizing, and hoisting to appropriate metadata, these interaction, and moving as much logic as possible from webpack's interpretation of `index.js` to a schema that can be used to:
- (optionally) validate a build _before_ webpack gets invoked
- build an optimized webpack bundle, as lab core and retro do
- let users build their own applications from the ground up with data, without invoking webpack _at all_. 

This is more of a lab 4.0 kind of thing, as it would require distributing every little piece of the application, _again_ as a federated extension, but, if completed, would _really_ get us in the lego-kit business, rather than finished-lego-sculpture-on-the-cover business, and who knows what folks would be able to do with it.

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jtpio/jupyterlab-app-template/pull/16

We'll continue iterating on that repo instead: https://github.com/jtpio/jupyterlab-app-template/pull/16

Which will eventually find a home in https://github.com/jupyterlab-contrib or https://github.com/jupyterlab.
