### ISSUE TITLE
Accessing /retro when running from jupyter notebook gives 404

### ISSUE THREAD

**Issue by yuvipanda** [jupyterlab/retrolab#149]
## Description

When I try to access retrolab via `/retro` URL on my running notebook server (not jupyter server server), I get a 404.

## Reproduce

```bash
pip install retrolab
jupyter notebook
```

In the browser that opens up, replace `/tree` with `/retrolab`

## Expected behavior

To see the awesomeness that's retrolab. 

## Context

- Operating System and version: Mac OS 11.2
- Browser and version: Firefox
- RetroLab version: 0.2.1

## More info

Is retrolab compatible only with jupyter server? I'd love for it to be compatible with notebook server as well - I suspect many extensions (such as https://github.com/jupyterhub/nbgitpuller/) will be notebook-server-only until they get fixed.

**Comment by jtpio** [comment]
Thanks @yuvipanda.

> Is retrolab compatible only with jupyter server?

I think it should also be compatible with the notebook server:

https://github.com/jupyterlab/retrolab/blob/b28c91c9adde90f429c5fca6b9d49b225fad0f92/setup.py#L48-L52

Since it works on Binder:

https://gist.github.com/jtpio/77c82c512f6779a1a05ab59d915dfc36

> In the browser that opens up, replace `/tree` with `/retrolab`

What happens when replacing with `/retro/tree`?

The redirect `/retro` -> `/retro/tree` was added in https://github.com/jupyterlab/retrolab/pull/138, which is available in `0.3.0a2`: https://pypi.org/project/retrolab/0.3.0a2/

Are you able to check with `0.3.0a2`? Then we could backport #138 to `0.2.x`.

**Comment by yuvipanda** [comment]
@jtpio aha, can confirm that works. How long do you think it'll take to get 0.3.0 out? I don't particularly need a backport now that I know of `/retro/tree`

**Comment by jtpio** [comment]
0.3.0 will probably follow a similar release cycle as JupyterLab 3.1. So no expected date yet.

**Comment by yuvipanda** [comment]
@jtpio ah, ok. in that case would <3 a backport

**Comment by jtpio** [comment]
@yuvipanda `0.2.2` is out: https://pypi.org/project/retrolab/0.2.2 with #138.

**Comment by jtpio** [comment]
Closing as fixed by #138 and #150
