### ISSUE TITLE
How to install JupyterLab extensions

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/retrolab#272]
### Problem

I am working with @jweill-aws to improve the retrolab shell to handle the L and R areas. Wondering if there is a way to install JupyterLab extensions that use the L/R area into retrolab - such as the table of contents, running panel, debugger, etc.

**Comment by jweill-aws** [comment]
Related issue: #268 

I've been working on adding left and right areas to RetroLab. I spent some time earlier today trying to bring the `toc-extension` and `toc` directories over from JupyterLab, but when I pulled in all the dependencies required to build that code, a single changelist included over 500 files. In addition, the extension expects to be added to an `ILabShell`, whereas RetroLab uses an `IRetroShell` interface. In addition, `TableOfContents` isn't properly recognized as a `Widget` because "`Type 'import("/Users/jweill/git/retrolab/packages/apputils/node_modules/@lumino/widgets/types/layout").Layout | null' is not assignable to type 'import("/Users/jweill/git/retrolab/node_modules/@lumino/widgets/types/layout").Layout | null'.`"

Although we have had a previous discussion about merging RetroLab into the JupyterLab simple interface (#257) the work I've been doing for #268 presumes that RetroLab will continue to exist on its own. The work I've done so far suggests that we might need data structures to bridge `ILabShell` with `IRetroShell` in order to use JupyterLab extensions like `toc` with both.

My work-in-progress branch for #268: https://github.com/jweill-aws/retrolab/tree/left-right-widgets

**Comment by jtpio** [comment]
Thanks @ellisonbg @jweill-aws.

As a first step we'll need to add support for the `left` and `right` areas in the `RetroShell`:

https://github.com/jupyterlab/retrolab/blob/2a96903699b66544a2c3c076cc5583e35d79dca7/packages/application/src/shell.ts#L200

Maybe we can use a `StackedPanel` without the `TabBar` to place the widgets in it.

Additional upstream dependencies and extensions are added to the `package.json` here:

https://github.com/jupyterlab/retrolab/blob/2a96903699b66544a2c3c076cc5583e35d79dca7/app/package.json#L94-L131

And listed here:

https://github.com/jupyterlab/retrolab/blob/2a96903699b66544a2c3c076cc5583e35d79dca7/app/package.json#L158-L229

And loaded here: 

https://github.com/jupyterlab/retrolab/blob/2a96903699b66544a2c3c076cc5583e35d79dca7/app/index.js#L156-L212

So for `@jupyterlab/toc-extension` the change should normally be pretty minimal.

Here is an example PR that added `@jupyterlab/hub-extension` to RetroLab: https://github.com/jupyterlab/retrolab/pull/148

**Comment by tonyfast** [comment]
are these left and right panels going to make significant visual changes relative to the classic interface? as we sunrise notebook, we've talked about having nearly the same interface as classic.

i think folks would love to use these tools. i could imagine the new features showing up over time. some stories i could imagine:

* i'm a user looking to write code and narrative in a classic notebook, i expect to see the form of the classic interface, if i don't the illusion is up
* i'm a user that writes markdown with headings in it, i'm alerted of the table of contents feature then i start outlining my ideas as a table of contents
* i'm a user writing code and throw an exception, the debugger alerts me of its existence.

if we are talking about adding the edges of retrolab, is the status bar a feature we'd like to have? while working in retro i find myself looking for a status bar that isn't there. it's a good feature of jupyterlab.

there is definitely precedence for these features. nbcontrib has a [table of contents](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/toc2/README.html) extensions that seems to dock on a side or float. they also add a navigate menu item that seems practical. there is definitely precen

**Comment by jtpio** [comment]
> are these left and right panels going to make significant visual changes relative to the classic interface? as we sunrise notebook, we've talked about having nearly the same interface as classic.

I think we should make them as invisible as possible to normal users wanting the most vanilla classic experience. Just like it is the case now. Hidden by default should be the *default*.

As hinted in https://github.com/jupyterlab/retrolab/issues/268#issuecomment-960622997, we should check the current behavior in classic when some nbextensions are installed (for example toc2).

> if we are talking about adding the edges of retrolab, is the status bar a feature we'd like to have?

Probably, but this should be hidden by default too. Otherwise we might end up re-implementing JupyterLab.

**Comment by jweill-aws** [comment]
@jtpio Thanks again for your detailed replies! I have a change in progress on [my development branch](https://github.com/jweill-aws/retrolab/tree/left-right-widgets) to add the `toc` extension. As you had suggested, it uses a `StackedPanel` and no `TabBar`. I ran into significant compilation problems after incorporating `toc-extension` by copying the contents of `packages/toc-extension` over from `jupyterlab` to `retrolab`. For example, `toc-extension` expects the shell to be an instance of `ILabShell`, but RetroLab instead uses `IRetroShell`.

After modifying the `toc-extension` code to use the appropriate shell interface, I found an error because of conflicts between versons of `@lumino/widgets`. See below. I can try to remove the added packages and instead modify the `package.json` file as you stated in your comment on Saturday. Thanks again for your help!

```
Argument of type 'TableOfContents' is not assignable to parameter of type 'Widget'.
  The types of 'title.owner.layout' are incompatible between these types.
  Type 'import("/Users/jweill/git/retrolab/packages/apputils/node_modules/@lumino/widgets/types/layout").Layout | null' is not assignable to type 'import("/Users/jweill/git/retrolab/node_modules/@lumino/widgets/types/layout").Layout | null'.
  Type 'import("/Users/jweill/git/retrolab/packages/apputils/node_modules/@lumino/widgets/types/layout").Layout' is not assignable to type 'import("/Users/jweill/git/retrolab/node_modules/@lumino/widgets/types/layout").Layout'.
  Types of property 'removeWidget' are incompatible.
  Type '(widget: import("/Users/jweill/git/retrolab/packages/apputils/node_modules/@lumino/widgets/types/widget").Widget) => void' is not assignable to type '(widget: import("/Users/jweill/git/retrolab/node_modules/@lumino/widgets/types/widget").Widget) => void'.
  Types of parameters 'widget' and 'widget' are incompatible.
  Type 'Widget' is missing the following properties from type 'Widget': hiddenMode, _hiddenMode
```

**Comment by jtpio** [comment]
> I ran into significant compilation problems after incorporating `toc-extension` by copying the contents of `packages/toc-extension` over from `jupyterlab` to `retrolab`. For example, `toc-extension` expects the shell to be an instance of `ILabShell`, but RetroLab instead uses `IRetroShell`.

We don't need to copy the `toc-extension` package to the retrolab repo. Instead we use the approach mentioned in https://github.com/jupyterlab/retrolab/issues/272#issuecomment-962424950 to incorporate it as an external dependency, so it can be reused as is.

At startup the `@jupyterlab/toc-extension` extension will add the widget to the `left` area: https://github.com/jupyterlab/jupyterlab/blob/114159269a76c4a8d4c1e725e882d7c8a7791869/packages/toc-extension/src/index.ts#L95

> For example, `toc-extension` expects the shell to be an instance of `ILabShell`, but RetroLab instead uses `IRetroShell`.

Ah right, I thought it was adding the widget via `app.shell` already. So from here we have two options:

1. make a PR to jupyterlab to add the toc via `app.shell` instead of `labShell`. So `labShell.add(toc, 'left', { rank: 400 });` becomes `app.shell.add(toc, 'left', { rank: 400 });`. We could then make the `ILabShell` dependency optional in the upstream `@jupyterlab/toc:plugin`: https://github.com/jupyterlab/jupyterlab/blob/114159269a76c4a8d4c1e725e882d7c8a7791869/packages/toc-extension/src/index.ts#L232
2. we start making `RetroShell` a `LabShell` (as discussed in https://github.com/jupyterlab/retrolab/issues/257#issue-1035446774)

It would have been nice to start with option 1, so we only add what is needed. Instead of taking the lab shell and trimming / hiding what we don't want.

> I found an error because of conflicts between versons of @lumino/widgets

Probably JupyterLab is using more recent versions of the Lumino packages. We can update them in RetroLab with by running this command:

```
jlpm run update:dependency --regex @lumino/ latest
```

**Comment by jtpio** [comment]
> 1. make a PR to jupyterlab to add the toc via `app.shell` instead of `labShell`

For reference there were a couple of upstream PRs to make some of the plugins more easily reusable in RetroLab. For example:

- https://github.com/jupyterlab/jupyterlab/pull/9667
- https://github.com/jupyterlab/jupyterlab/pull/9467
- https://github.com/jupyterlab/jupyterlab/pull/9442
- https://github.com/jupyterlab/jupyterlab/pull/9439

**Comment by jweill-aws** [comment]
Thanks again! I'm working on removing `ILabShell` from `packages/toc-extension/src/index.ts`, replaces references to `labShell` with `app.shell`, but this line now indicates an error because `currentChanged` is not a property of `IShell`:
https://github.com/jupyterlab/jupyterlab/blob/114159269a76c4a8d4c1e725e882d7c8a7791869/packages/toc-extension/src/index.ts#L192-L193

I'll see if I can do a little more refactoring. Should I open an issue in @jupyterlab/jupyterlab to capture this work?

**Comment by jtpio** [comment]
> this line now indicates an error because `currentChanged` is not a property of `IShell`:

Right. So usually we make `ILabShell` an `optional` dependency (instead of `requires`). And guard the access to `currentChanged` with `if (labShell) {}`. This pattern is heavily used across the jupyterlab code base.

**Comment by jweill-aws** [comment]
Created issue and PR (https://github.com/jupyterlab/jupyterlab/pull/11420) mentioned above to modify the `toc` extension for compatibility with RetroLab.

**Comment by jtpio** [comment]
Also if we want to move forward with this, we can temporarily vendor the code in the `toc-extension`: https://github.com/jupyterlab/jupyterlab/blob/master/packages/toc-extension/src/index.ts.

And add it to https://github.com/jupyterlab/retrolab/blob/main/packages/application-extension/src/index.ts for now to avoid creating a new package since it's temporary anyway.

Until a new release of the upstream `@jupyterlab` includes the change in https://github.com/jupyterlab/jupyterlab/pull/11420. Then we can remove the vendored code and use the approach mentioned in https://github.com/jupyterlab/retrolab/issues/272#issuecomment-962424950.

That way we can still make progress and start opening a draft PR.

**Comment by jweill-aws** [comment]
Closing in favor of https://github.com/jupyter/notebook/issues/6326.
